# Generated by Django 5.0.6 on 2024-06-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(choices=[('AP', 'Andhra Pradesh'), ('KA', 'Karnataka')], default='KA', max_length=2),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(max_length=6),
        ),
    ]
