# Generated by Django 5.0.6 on 2024-07-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
