# Generated by Django 5.0.6 on 2024-06-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsquare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='engine',
            new_name='product_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='transmisson',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='vin',
        ),
        migrations.AddField(
            model_name='listing',
            name='dimensions',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default='900', max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='sku',
            field=models.CharField(default='10', max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='brand',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
