# Generated by Django 5.0.6 on 2024-06-30 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsquare', '0003_rename_dimensions_listing_size_alter_listing_price_and_more'),
        ('users', '0002_alter_location_state_alter_location_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location'),
        ),
    ]
