# Generated by Django 5.0.6 on 2024-07-17 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketsquare', '0005_alter_listing_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='product_type',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='size',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='weight',
        ),
    ]
