# Generated by Django 5.1.1 on 2024-09-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsquare', '0006_rename_product_type_listing_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('under_review', 'Under Review')], default='active', max_length=15),
        ),
        migrations.AddField(
            model_name='listing',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
