# Generated by Django 5.1.1 on 2024-09-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsquare', '0007_listing_category_listing_condition_listing_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('furniture', 'Furniture'), ('accessories', 'Accessories'), ('footwear', 'Footwear'), ('others', 'Others')], max_length=50, null=True),
        ),
    ]
