# Generated by Django 5.1.1 on 2024-09-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsquare', '0008_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('furniture', 'Furniture'), ('accessories', 'Accessories'), ('smartphones', 'Smartphones'), ('shoes', 'Shoes'), ('gaming console', 'Gaming Console'), ('television', 'Television'), ('laptops', 'Laptops'), ('watches', 'Watches'), ('furniture', 'Furniture'), ('footwear', 'Footwear'), ('books', 'Books'), ('musical instruments', 'Musical Instruments'), ('sports equipment', 'Sports Equipment'), ('home appliances', 'Home Appliances'), ('others', 'Others')], max_length=50, null=True),
        ),
    ]
