# Generated by Django 5.1.1 on 2024-09-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsquare', '0010_alter_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
